### ISSUE TITLE
Dataset Asking

### ISSUE THREAD

**Issue by windring** [Veleslavia/vimss#4]
Hello, very sorry, where can I find the train/val/test division of URMP used in this project (paper), thank you very much

**Comment by Veleslavia** [comment]
Hi @windring,
Sorry, but I no longer have access to the data and configs for this project, so I can't provide the exact splits. 
From what I can recall, we only used train and test splits, 33 pieces in train and 11 in test (no validation was performed during training), and we created the splits manually trying to have all instruments present in the train split. I think if you check the distribution of individual instruments in URMP pieces, there will be very few possible ways to have all possible combinations of instruments and ensemble types in train.

**Comment by windring** [comment]
Thank you very much for your reply! I will carefully consider your comments, thank you very much!
